### ISSUE TITLE
LERF fails with brandenburg-gate

### ISSUE THREAD

**Issue by machenmusik** [kerrj/lerf#10]
This works (Nerfacto)
`ns-train nerfacto --data data\phototourism\brandenburg-gate phototourism-data`

This fails
`ns-train lerf --data data\phototourism\brandenburg-gate phototourism-data`
with
```
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 685 but got size 1028 for tensor number 1
in the list.
```

**Comment by kerrj** [comment]
We haven't tested this with other dataparsers than the nerfstudio dataparser, I'm not sure if the code is compatible with the phototourism dataset. Is it possible to use the standard nerfstudio dataset instead? If not there might need to be a bit of code to port over LERF dataloading into the phototourism dataparser(see lerf_datamanager.py)

**Comment by kerrj** [comment]
Closing this now, though integrating other dataparsers/datasets would be a nice future TODO
