### ISSUE TITLE
How to get VSCode working with NerfStudio

### ISSUE THREAD

**Issue by acube3** [kerrj/lerf#11]
What do you mean by?
Connect to the viewer by forwarding the viewer port (we use VSCode to do this), and click the link to viewer.nerf.studio provided in the output of the train script. How do you visualize in VSCode?Is experience different in VSCode vs browser?

**Comment by kerrj** [comment]
Hi!
This part is mainly relevant if you're using a remote server GPU that isn't on your local machine. In that case, to connect to the viewer from your local browser you need to forward the viewer port from server to local machine. One way of doing this is with VSCode, as specified [here](https://code.visualstudio.com/docs/remote/ssh#:~:text=Once%20you%20are%20connected%20to,button%20in%20the%20Ports%20view.).

If you're training on the same machine you're visualizing on, this step wouldn't be necessary.
