### ISSUE TITLE
ns-install-cli creates  _ns-export with error message.

### ISSUE THREAD

**Issue by karun2016** [kerrj/lerf#18]
I followed the instructions for installing lerf with nefstudio in Conda env.
Steps 0, 1,2 and 3 ( Run ns-install-cli)
Everything went well.
But when I try to activate the conda env, 
I get this message:
***
Warning:: command not found
Unable: command not found
libio_e57.so:: command not found
-bash: ~/anaconda3/envs/lerf_nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/_ns-export: line 6: syntax error near unexpected token `('
-bash: ~/anaconda3/envs/lerf_nerfstudio/lib/python3.8/site-packages/scripts/completions/bash/_ns-export: line 6: `Cannot load library ~/anaconda3/envs/lerf_nerfstudio/lib/python3.8/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)'
***
This is due to ' __ns-export'   not generated properly. But I did not any error message in step 3. ns-install-cli --mode install.

Any suggestion. Should I just ignore it?
 I can just comment those warning messages lines for now.

**Comment by kerrj** [comment]
That's strange, it seems like some problem with the conda environment? if there's no other errors it's probably safe to ignore, ns-install-cli is mainly just responsible for tab completion on the CLI

**Comment by karun2016** [comment]
Thank you. 
Got it.  don't think anything special about my conda env. I just created a new env with the steps for nerfstutioa nd then followed your instructions here. I will double check my conda env.

**Comment by kerrj** [comment]
Going to close this now, let us know if things are still broken!

**Comment by MildCloud** [comment]
Meet the same problem, should I fix something or just ignore the warning?
