### ISSUE TITLE
Bug in patch sampling

### ISSUE THREAD

**Issue by gtangg12** [kerrj/lerf#19]
Hello, for patch sampling, I think using torch.searchsorted(...) -1 leads to bugs

For example, consider x_center = tensor([  0.,  87., 174., 261., 348., 435., 522., 609.]) and some sample points = tensor([ 87, 609, 348, 522, 174, 261, 0, 348, 609, 609,  87, 435, 174, 0, 522, 435, 522, 522])

Using torch.searchsorted(...) leads to tensor([ 0,  6,  3,  5,  1,  2, -1,  3,  6,  6,  0,  4,  1, -1,  5,  4,  5,  5])
Instead, you can just do 

`x_ind = torch.floor((x - (self.center_x[0])) / self.stride).long()`

which produces tensor([1, 7, 4, 6, 2, 3, 0, 4, 7, 7, 1, 5, 2, 0, 6, 5, 6, 6]).

**Comment by chungmin99** [comment]
Hi! I was able to replicate the bug :) Seems like we never caught it because `-1` would let the indices wrap around and avoid crashing. 

I believe your suggested fix should work (also tested your suggestions locally), do you want to make a PR for it?

**Comment by chungmin99** [comment]
Corresponding code was merged a few weeks ago -- closing issue
