### ISSUE TITLE
Missing scene "Table"

### ISSUE THREAD

**Issue by noahstier** [kerrj/lerf#21]
The paper uses a scene called "Table" for evaluation but I don't see that scene in the [dataset](https://drive.google.com/drive/folders/1LUzwEvBCE19PNYcwfmrG-9FLpZLbi4on) or [videos](https://drive.google.com/drive/folders/1wyg3JXQu2PHTENVCW-F8o0EvUHsb_HAa) that are linked from the project website. Is that intentional?

**Comment by kerrj** [comment]
Sorry for the late reply! There are some people's faces in the table dataset so for privacy we're working on getting their approval to release, hopefuly it should be up soon.
