### ISSUE TITLE
Scene Redering isn't working on Nerfstudio

### ISSUE THREAD

**Issue by PhucNDA** [kerrj/lerf#24]
Hi, thanks for the wonderful project.

I have followed the Lerf detailed instruction for installation on the latest version of the Nerfstudio.
Take the "bookstore" dataset for example. The training does go on with multi-view images but the scene rendering is not working. I don't know if the visualization phase has not been yet fully adopted when integrated to Nerfstudio. With the same dataset, Nerfactor does render the full scene.

Correct me if I am wrong or something.
Again, thanks for significant work.

**Comment by atonderski** [comment]
I have the same (or similar) issue!
The only option for the output renderer is "not set", so something probably crashes along the way. The training progresses smoothly though. Will debug more tomorrow, but let me know if you find the issue.

**Comment by kerrj** [comment]
Could you provide some more information about the crashes? if rendering is crashing in the viewer it should print an error message from the render thread in the terminal output. Try setting `--logging.local-writer.max-log-size 0` to prevent over-writing output error messages in the logging too.

**Comment by PhucNDA** [comment]
![error_rendering](https://github.com/kerrj/lerf/assets/108280892/e0ebca16-61d1-4f65-9e62-2bf69492be54)
 Here's the example of the scene rendering is not working as the training procedure goes on.

I use the **torch==1.12.1+cu113 torchvision==0.13.1+cu113**. The others follow the setup file of Lerf, instead, I use the downgraded [functorch](https://github.com/pytorch/functorch/releases) version of 0.2.1. This environment can work well with other method (nerfacto,...). I'm still trying to debug the error, but I guess it is because of the overridden function `get_outputs_for_camera_ray_bundle`.

> Could you provide some more information about the crashes? if rendering is crashing in the viewer it should print an error message from the render thread in the terminal output. Try setting `--logging.local-writer.max-log-size 0` to prevent over-writing output error messages in the logging too.

**Comment by kerrj** [comment]
Hm that's strange, let me know if you find an error message. It could also be worth upgrading pytorch/cuda driver, 1.12 is quite old (nerfstudio is going to support >2.0 going forward)

**Comment by PhucNDA** [comment]
>

**Comment by atonderski** [comment]
@PhucNDA did you find a fix for this?

**Comment by PhucNDA** [comment]
Yes, the author has just recently comitted the version of **0.1.1** which addresses our issue:
![image](https://github.com/kerrj/lerf/assets/108280892/302c15e8-4f9a-42ee-85dc-d872ec901894)

> @PhucNDA did you find a fix for this?

**Comment by anas-zafar** [comment]
Hi @PhucNDA , could you please guide me regarding the training. I followed the instructions. Downloaded the bookstore data for example. When I try to run the training, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/usr/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/usr/lib/python3.9/site-packages/nerfstudio/configs/method_configs.py", line 53, in <module>
    from nerfstudio.models.depth_nerfacto import DepthNerfactoModelConfig
  File "/usr/lib/python3.9/site-packages/nerfstudio/models/depth_nerfacto.py", line 30, in <module>
    from nerfstudio.models.nerfacto import NerfactoModel, NerfactoModelConfig
  File "/usr/lib/python3.9/site-packages/nerfstudio/models/nerfacto.py", line 27, in <module>
    from torchmetrics.functional import structural_similarity_index_measure
  File "/usr/lib/python3.9/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 120, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "/usr/lib/python3.9/site-packages/torchmetrics/functional/text/__init__.py", line 18, in <module>
    from torchmetrics.functional.text.edit import edit_distance
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 978, in get_code
  File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode
EOFError: marshal data too short
```
