### ISSUE TITLE
ns-install-cli error

### ISSUE THREAD

**Issue by aimeeguo24** [kerrj/lerf#28]
Hello!
When I try to run step 3 ns-install-cli , it shows the following error:
$HOME is not set. Exiting.              install.py:353
I'm not sure how to fix this error, and I followed the installation process up to step 3 but am stuck here. Can you please help me on this?
Thanks!

**Comment by DrMemoryFish** [comment]
same

**Comment by DrMemoryFish** [comment]
> Hello! When I try to run step 3 ns-install-cli , it shows the following error: $HOME is not set. Exiting. install.py:353 I'm not sure how to fix this error, and I followed the installation process up to step 3 but am stuck here. Can you please help me on this? Thanks!

I found a solution: 

In Windows, the $HOME environment variable may not be set by default. However, you can manually set it before running the ns-install-cli command. Here's how you can do it:

Open the Command Prompt.

Run the following command to set the $HOME variable to your user directory (C:\Users\*your username*):

`set HOME=%USERPROFILE%`

This command sets the $HOME variable to the path of your user directory, typically C:\Users\username.

After setting the $HOME variable, try running the ns-install-cli command again:

`ns-install-cli`

Setting the $HOME variable to your user directory should resolve the error related to $HOME not being set.

**Comment by kerrj** [comment]
This seems resolved, if it's still an issue feel free to re-open. Also, errors in ns-install-cli will just affect the command line tab completion, you could still execute the training commands etc.
