### ISSUE TITLE
Ground-truth labels for localization evaluation

### ISSUE THREAD

**Issue by shengjie-lin** [kerrj/lerf#29]
Dear authors of LERF, thanks for sharing this phenomenal work!
In section 4.3 of your [paper](https://arxiv.org/pdf/2303.09553.pdf), you "label bounding boxes for 72 objects across 5 scenes". I checked the [dataset link](https://drive.google.com/drive/folders/1vh0mSl7v29yaGsxleadcj-LCZOE_WEWB) and it seems that the ground-truth labels are not included. I wonder if you can share a labeled version of dataset so that people can potentially reproduce numbers in the paper.
Thanks!

**Comment by chungmin99** [comment]
Addressed in #27, the data should be available in the google drive :)
