### ISSUE TITLE
Debbuging nerfstudio project

### ISSUE THREAD

**Issue by linukc** [kerrj/lerf#31]
@kerrj This is a great project and awesome example of how to build a new method using Nerfstudio, thanks to you and other authors. However for me as a newbie it is unclear how to debug such a project. Maybe as a LERF developer you can share some instructions on how you did it. I use VSCode.

**Comment by linukc** [comment]
https://github.com/nerfstudio-project/nerfstudio/issues/2098

**Comment by immortalmin** [comment]
You can use pdb.
After completing the preparation work for nerfstudio and lerf, insert the following code at the beginning of the file you want to debug, 
```
import pdb
pdb.set_trace()
```
and then run the ns-train command directly, such as
`ns-train lerf --data <data_folder>`
you can enter debug mode. 
For more debug commands, please refer to the [official documentation of pdb](https://docs.python.org/3/library/pdb.html)
