### ISSUE TITLE
Typo: definition of scale s(t)

### ISSUE THREAD

**Issue by sangminkim-99** [kerrj/lerf#33]
Hello, @kerrj!

Thank you for sharing this excellent work!

While reading the paper, I noticed a typo.
In Section 3.1, the scale s(t) is defined as follows:
$s(t) = s_{img} \times f_{xy} / t$.

However, the correct definition of s(t) should be:
$s(t) = s_{img} \times t / f_{xy}$.

I kindly request a modification to reflect the accurate information. Thank you!

**Comment by chungmin99** [comment]
Thank you for bringing this up to our attention! You're correct, we just fixed this in our working draft. 

This typo should be corrected in the next version of our arxiv submission.
