### ISSUE TITLE
Language loss

### ISSUE THREAD

**Issue by Vinayak-VG** [kerrj/lerf#36]
In the paper it is mentioned that, you are maximising the cosine loss between the clip vector and the predicted vector but in the code it seems to be that you are using a huber loss. So could you please clarify this if possible

**Comment by kerrj** [comment]
Hi sorry for the late reply! Huber and MSE are very similar losses in the range of cosine similarity scores (-1->1), but we found using huber/l1 instead of MSE resulted in very slightly better performance (this change happened since the paper arxiv).
