### ISSUE TITLE
No textbox in viewer

### ISSUE THREAD

**Issue by jiadingfang** [kerrj/lerf#5]
Hi Justin,

Thanks for the great work and the code release for LERF!

I tried to follow the instructions in this repo to run lerf and have successfully trained a lerf-lite model on my custom data. However, even if I build custom viewer as you suggested and use `yarn start` to launch and connect it with my local training port, when I open the viewer, it looks like a regular nerfstudio viewer and I cannot find a text box as you showed in the demo to search even I selected `relevancy_0` field. The following is a screenshot (the resolution is pretty low, I'll use a better machine to render later)

![image](https://user-images.githubusercontent.com/16885585/232549938-27a382c1-7184-40da-a7f0-108120e40d20.png)

Can you kindly suggest where could I did wrong here?

Best,
JD

**Comment by chungmin99** [comment]
Hi! Thanks for your interest in the project.

The textbox is located here, at `clip_pos_word` (in red circle):
<img width="1772" alt="image" src="https://user-images.githubusercontent.com/10284938/232551807-51f47944-02e3-45fc-be9c-b1248eeeec74.png">

Let us know if that works!

**Comment by chungmin99** [comment]
P.S. we're also working on integrating the new nerfstudio viewer with this codebase (hopefully by tomorrow), which should make the viewer more user-friendly. :)

**Comment by zijianh4** [comment]
Hi,
It seems that the nerfstudio is updated. Could you please tell me where is the textbox now? Thanks!
<img width="770" alt="image" src="https://github.com/kerrj/lerf/assets/36258633/f5bd6940-d4e2-4ed1-a5b5-a5949fe76e44">
